### ISSUE TITLE
"State" as strings

### ISSUE THREAD

**Issue by awickert** [bld456/CompMethodsProject#3]
Would it be more straightforward to have the user just pass a string directly to "state" for steady or transient?

```
    #state = 0 corresponds to steady-state
    #dim controls how many dimensions will be considered, currently only 1d is supported
    def __init__(self, state, dim):
        self.BC = np.zeros((1,3))

        if state == 0:
            self.state = 'steady'
        else:
           self.state = 'transient'
            #Demand that changing head with time data be added/calculated

        if dim == 1:
            self.dim = 1
        else:
            raise ValueError('Only one dimension is supported in this release' )
            #higher dimention functionallity not implemented
```

**Comment by jacktlange** [comment]
Yeah! I updated the code to reflect this change

    def __init__(self, state, dim):
        self.BC = np.zeros((1,3))
        
        if state == 'steady' or state =='transient':
            self.state = state
        else:
            raise ValueError('The state was not specifiend properly' )
        
        if dim == 1:
            self.dim = 1
        else:
            raise ValueError('Only one dimension is supported in this release' )
            #higher dimention functionallity not implemented
